version: '3.8'
services:
  db:
    container_name: spring-db
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - path:/var/lib/spring-db

  backend:
    container_name: spring-backend
    image: master-thesis-spring
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8081"
      - "9010:9010"
    depends_on:
      - db

volumes:
  path:
    driver: local
