version: '3.8'
services:
  db:
    container_name: quarkus-db
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    ports:
      - '5432:5432'
    volumes:
      - path:/var/lib/quarkus-db

  backend:
    container_name: quarkus-backend
    image: master-thesis-quarkus-native
    ports:
      - "8081:8081"
      - "9010:9010"
    depends_on:
      - db

volumes:
  path:
    driver: local
