CREATE TABLE app_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    surname    VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uc_user_email UNIQUE (email),
    CONSTRAINT uc_user_username UNIQUE (username)
);

CREATE TABLE product
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    price          DOUBLE PRECISION                        NOT NULL,
    description    VARCHAR(255)                            NOT NULL,
    rating         DOUBLE PRECISION                        NOT NULL,
    user_id        BIGINT,
    category_type  VARCHAR(128),
    condition_type VARCHAR(128),
    offer_type     VARCHAR(128),

    CONSTRAINT pk_product PRIMARY KEY (id),
    CONSTRAINT FK_PRODUCT_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id)
);
